input_polygons:
  datasets:
    - ./vektor_praktikum/vektor_jalan.sqlite
      uniqueid: id
      lifting: Road
      height_field: id
    - ./vektor_praktikum/vektor_bangunan.sqlite
      uniqueid: orig_oid
      lifting: Building
      height_field: status

lifting_options:
  Building:
    lod: 1
    floor: true
    inner_walls: true
    triangulate: false
    ground:
      height: percentile-10
      use_LAS_classes:
        - 2
    roof:
      height: percentile-90
      use_LAS_classes:
        - 6
  Road:
    height: percentile-50
    use_LAS_classes:
      - 2

input_elevation:
  datasets:
    - ./lidar/lidar_sebatik.las
  omit_LAS_classes:
    - 0   # Never classified
    - 1   # Unclassified
  thinning: 0

options:
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.5
